<?php
echo '<html>';
echo '';
echo '<title>Student registration</title>';
echo '';
echo '<h1>Student Registration Form </h1>';
echo '';
echo '<body>';
echo '';
echo '<form method=get action="">';
echo '';
echo 'Enter Student Id:<input type=text name=t1 value="<?php if(isset($_GET['t1'])) echo $_GET['t1'];?>"></br>';
echo '';
echo 'Enter Student Family Name:<input type=text name=t2 value="<?php if(isset($_GET['t2'])) echo $_GET['t2'];?>"></br>';
echo '';
echo 'Enter Student First Name:<input type=text name=t3 value="<?php if(isset($_GET['t3'])) echo $_GET['t3'];?>"></br>';
echo '';
echo 'Enter Student Middle Name:<input type=text name=t4 value="<?php if(isset($_GET['t4'])) echo $_GET['t4'];?>"></br>';
echo '';
echo 'Enter Home Address:<input type=text name=t5 value="<?php if(isset($_GET['t5'])) echo $_GET['t5'];?>"></br>';
echo '';
echo 'Enter Mobile Number:<input type=text name=t6 value="<?php if(isset($_GET['t6'])) echo $_GET['t6'];?>"></br>';
echo '';
echo 'Enter Student Course:<input type=text name=t7 value="<?php if(isset($_GET['t7'])) echo $_GET['t7'];?>"></br>';
echo '';
echo '<input type=submit value=submit></br>';
echo '';
echo '</form>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
echo '<?php';
echo '';
echo 'if(isset($_GET['t1']))';
echo '';
echo '{';
echo '';
echo 'if($Id==""||$FamilyName==""||$FirstName==""||$MiddleName==""||$Address==""||$Number==""||$Course=="")';
echo '';
echo '{';
echo '';
echo 'echo "All fields are compulsory :";';
echo '';
echo '}';
echo '';
echo 'else';
echo '';
echo '{';
echo '';
echo '$Id=$_GET['t1'];';
echo '';
echo '$FamilyName=$_GET['t2'];';
echo '';
echo '$cFirstName=$_GET['t3'];';
echo '';
echo '$MiddleName=$_GET['t4'];';
echo '';
echo '$Address=$_GET['t5'];';
echo '';
echo '$Number=$_GET['t6'];';
echo '';
echo '$Course=$_GET['t7'];';
echo '';
echo 'echo "<h1>Student Information </h1></br>";';
echo '';
echo 'echo "Student Id :$Id</br>";';
echo '';
echo 'echo "Student Family Name: $FamilyName</br>";';
echo '';
echo 'echo "Student First Name: $FirstName</br>";';
echo '';
echo 'echo "Student Middle Name :$MiddleName</br>";';
echo '';
echo 'echo "Student Address: $Address</br>";';
echo '';
echo 'echo "Student Mobile Number: $Number</br>";';
echo '';
echo 'echo "Student Course: $Course</br>";';
echo '';
echo '';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '}';
echo '';
echo '';
echo '?>';
?>